spring.application.name=HowManyCals

# JWT
jwt.secret=KSUProject2026@HowManyCalsSecretKey
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=15552000000

# H2
spring.datasource.url=jdbc:h2:mem:howmanycals
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Food Image
food.image.temp-dir=./uploads/temp
food.image.max-file-size=5242880

# AI Server
ai.server.analyze-url=https://jbhy4hw3l5ijaw9f8y42ugkjqdfg.online/api/v1/analyze
ai.server.api-key=be7ZMHSE2M3KEqqUHg5VWwUmRCdD8AaFrsIbRkuX97ycYBN7IZqFGqKAvSmfjYNxp3EWe3AxVYdcXdpB4FNFNK5CcyEPy6yPTIwxINr5dNmQZXVksMZYtekhjg7hGZvEAz2KQKWQSNa53cVTdfNFZha5eyVNPtXeKQI3QPuFAygJcxkGN4BwVbxhwwQTd8dwsbt4dSJHdaXstb3IzPDxVISepTpusDuIVJuMhyYWs4HJgNEhDJ9B8DSbJ3gaaGRe
ai.server.callback-url=http://ec2-3-26-148-236.ap-southeast-2.compute.amazonaws.com:8080/api/ai/callback

# OAuth - Kakao
oauth.kakao.client-id=
oauth.kakao.client-secret=
oauth.kakao.redirect-uri=http://localhost:8080/auth/oauth/kakao/callback

# OAuth - Google
oauth.google.client-id=
oauth.google.client-secret=
oauth.google.redirect-uri=http://localhost:8080/auth/oauth/google/callback

# OAuth - Naver
oauth.naver.client-id=
oauth.naver.client-secret=
oauth.naver.redirect-uri=http://localhost:8080/auth/oauth/naver/callback

