spring.application.name=HowManyCals

# JWT
jwt.secret=KSUProject2026@HowManyCalsSecretKey
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

# H2 ???? DB
spring.datasource.url=jdbc:h2:mem:howmanycals
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=test
spring.datasource.password=

# H2 ?? (?????? DB ??: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
